version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meu_banco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
